name: NPCSystem
version: '${project.version}'
main: chatzis.nikolas.mc.npcsystem.NPCSystem
api-version: '1.20'
authors: [Nikolas Chatzis]

depend:
  - NikoAPI

commands:
  npcdebug:
    usage: /<command>